### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by razoreater** [rubensworks/rdf-stores.js#5]
Hi,

I have been toying around with this repo, and I have some questions:

Is it possible to use the results of the `getQuads` or `readQuads` methods as values for the `import` or `addQuads` methods?
Or can this only be done through manually  defining the quads.

Thanks in advance!

**Comment by rubensworks** [comment]
Sure, that should work!

**Comment by razoreater** [comment]
Great! Any pointers how I can do this?

Should I split the subject, predicate and object for every record or can I do this trough easier means.

I'm kind of new to Javascript.
Thanks in advance!

**Comment by razoreater** [comment]
I managed to solve it using an import.
Thanks for you time today 🥇
